"""
Security Setup Script for IoT Smart Home System
Generates SSL certificates and sets up security environment
"""
import os
import subprocess
import secrets
from pathlib import Path

def create_ssl_certificates():
    """Create self-signed SSL certificates for development"""
    certs_dir = Path("certs")
    certs_dir.mkdir(exist_ok=True)
    
    # Generate private key
    key_cmd = [
        "openssl", "genrsa", 
        "-out", str(certs_dir / "server.key"), 
        "2048"
    ]
    
    # Generate certificate signing request
    csr_cmd = [
        "openssl", "req", 
        "-new", "-key", str(certs_dir / "server.key"),
        "-out", str(certs_dir / "server.csr"),
        "-subj", "/C=US/ST=State/L=City/O=IoT/CN=localhost"
    ]
    
    # Generate self-signed certificate
    crt_cmd = [
        "openssl", "x509", 
        "-req", "-days", "365",
        "-in", str(certs_dir / "server.csr"),
        "-signkey", str(certs_dir / "server.key"),
        "-out", str(certs_dir / "server.crt")
    ]
    
    try:
        print("Generating SSL certificates...")
        subprocess.run(key_cmd, check=True, capture_output=True)
        subprocess.run(csr_cmd, check=True, capture_output=True)
        subprocess.run(crt_cmd, check=True, capture_output=True)
        
        # Clean up CSR file
        os.remove(certs_dir / "server.csr")
        
        print(f"✓ SSL certificates generated in {certs_dir}/")
        print("  - server.key (private key)")
        print("  - server.crt (certificate)")
        
    except subprocess.CalledProcessError as e:
        print(f"Error generating certificates: {e}")
        print("Make sure OpenSSL is installed and available in PATH")
    except Exception as e:
        print(f"Unexpected error: {e}")

def generate_security_keys():
    """Generate security keys and create .env file"""
    env_content = f"""# IoT Smart Home Security Configuration
# Generated by security_setup.py

# API Keys
IOT_API_KEY={secrets.token_urlsafe(32)}
GATEWAY_API_KEY={secrets.token_urlsafe(32)}

# JWT Configuration
JWT_SECRET_KEY={secrets.token_urlsafe(64)}
JWT_EXPIRATION_HOURS=24

# Device-specific keys
ROOF_STATION_KEY={secrets.token_urlsafe(32)}
LIVING_ROOM_KEY={secrets.token_urlsafe(32)}
KITCHEN_KEY={secrets.token_urlsafe(32)}
DUST_CLEANER_KEY={secrets.token_urlsafe(32)}
BEDROOM_KEY={secrets.token_urlsafe(32)}
BASEMENT_KEY={secrets.token_urlsafe(32)}
ENTRANCE_KEY={secrets.token_urlsafe(32)}

# SSL Configuration
SSL_ENABLED=false
SSL_CERT_PATH=./certs/server.crt
SSL_KEY_PATH=./certs/server.key

# Security Features
ENABLE_REQUEST_SIGNING=true
ENABLE_DATA_ENCRYPTION=false
RATE_LIMIT_PER_MINUTE=60

# Database
MONGODB_URI=mongodb://localhost:27017/
MONGODB_DATABASE=IOT_SECURE

# Server Configuration
CONTROLLER_HOST=localhost
CONTROLLER_PORT=5000
SENSOR_SERVICE_PORT=5001
GATEWAY_PORT=5002

# CORS
CORS_ORIGINS=http://localhost:3000,https://localhost:3000

# Logging
LOG_LEVEL=INFO
"""
    
    with open('.env', 'w') as f:
        f.write(env_content)
    
    print("✓ Security configuration saved to .env")
    print("✓ Generated secure API keys and JWT secrets")

def create_security_documentation():
    """Create security documentation"""
    docs_content = """# IoT Smart Home Security Guide

## Security Features Implemented

### 1. Authentication & Authorization
- **API Key Authentication**: Required for system endpoints
- **JWT Tokens**: Device-specific authentication with expiration
- **Device Keys**: Unique keys per sensor device
- **Gateway Authentication**: Separate key for gateway service

### 2. Data Protection
- **Request Signing**: HMAC-SHA256 signatures for data integrity
- **Optional Encryption**: AES encryption for sensitive sensor data
- **Secure Headers**: Security headers to prevent common attacks

### 3. Network Security
- **HTTPS Support**: SSL/TLS encryption for all communications
- **Certificate Validation**: Verify SSL certificates
- **Rate Limiting**: Prevent abuse with request rate limits

### 4. Access Control
- **Device Isolation**: Each device has unique credentials
- **Endpoint Protection**: Different authentication levels per endpoint
- **Token Expiration**: JWT tokens automatically expire

## API Endpoints Security

### Device Authentication Required:
- `POST /api/sensor-data` - Requires JWT token + signature
- Device must authenticate before sending sensor data

### API Key Required:
- `GET /api/status` - System status
- `POST /api/actuators/<id>` - Actuator control
- `POST /api/device/token` - Generate device tokens

### Gateway Authentication Required:
- `POST /api/sensor-data/gateway` - Gateway-filtered data

## Usage Instructions

### 1. Generate Device Token
```bash
curl -X POST http://localhost:5000/api/device/token \\
  -H "X-API-Key: YOUR_API_KEY" \\
  -H "Content-Type: application/json" \\
  -d '{"device_id": "roof_station"}'
```

### 2. Send Sensor Data
```bash
curl -X POST http://localhost:5000/api/sensor-data \\
  -H "Authorization: Bearer JWT_TOKEN" \\
  -H "X-Signature: REQUEST_SIGNATURE" \\
  -H "Content-Type: application/json" \\
  -d '{"device_id": "roof_station", "readings": [...]}'
```

### 3. Enable HTTPS
1. Set `SSL_ENABLED=true` in .env
2. Ensure certificates exist in ./certs/
3. Update client URLs to use https://

## Security Best Practices

1. **Environment Variables**: Store all keys in .env file
2. **Certificate Management**: Use proper CA-signed certificates in production
3. **Key Rotation**: Regularly rotate API keys and JWT secrets
4. **Monitoring**: Monitor failed authentication attempts
5. **Network**: Use VPN or private networks when possible

## Troubleshooting

### Authentication Errors
- Check device keys in configuration
- Verify JWT token hasn't expired
- Ensure request signature is correctly calculated

### SSL/TLS Issues
- Verify certificate files exist and are readable
- Check certificate validity dates
- Ensure proper certificate chain

### Rate Limiting
- Check if device is exceeding rate limits
- Increase limits if legitimate traffic is blocked
"""

    with open('SECURITY.md', 'w') as f:
        f.write(docs_content)
    
    print("✓ Security documentation saved to SECURITY.md")

def main():
    """Run security setup"""
    print("IoT Smart Home Security Setup")
    print("=" * 40)
    
    # Generate security keys and environment
    generate_security_keys()
    
    # Create SSL certificates
    create_ssl_certificates()
    
    # Create documentation
    create_security_documentation()
    
    print("\n" + "=" * 40)
    print("Security setup complete!")
    print("\nNext steps:")
    print("1. Review the .env file and adjust settings as needed")
    print("2. Install dependencies: pip install -r backend/requirements.txt")
    print("3. Read SECURITY.md for usage instructions")
    print("4. Test the secure endpoints with proper authentication")

if __name__ == "__main__":
    main()